Imports System.Xml

Imports PDMWorks

Module create_part

    Sub Main()
        If My.Application.CommandLineArgs.Count < 3 Then
            Console.WriteLine("Usage: create_part.exe Project Name Description")
            Return
        End If

        Dim project As String = My.Application.CommandLineArgs(0)
        Dim name As String = My.Application.CommandLineArgs(1)
        Dim description As String = My.Application.CommandLineArgs(2)
        Dim filename As String = name + ".sldprt"

        Dim host As String = "localhost"
        Dim username As String = "pdmwadmin"
        Dim password As String = "pdmwadmin"
        Dim reader As XmlTextReader = New XmlTextReader("WPDM.config")
        reader.WhitespaceHandling = WhitespaceHandling.None
        reader.Read()
        reader.Read()
        While Not reader.EOF
            reader.Read()
            If reader.Name.Equals("WPDMHost") Then
                reader.Read()
                host = reader.Value
                reader.Read()
            ElseIf reader.Name.Equals("WPDMUsername") Then
                reader.Read()
                username = reader.Value
                reader.Read()
            ElseIf reader.Name.Equals("WPDMPassword") Then
                reader.Read()
                password = reader.Value
                reader.Read()
            End If
        End While

        Dim connection As PDMWConnection = CreateObject("PDMWorks.PDMWConnection")
        Try
            connection.Login(username, password, host)
            My.Computer.FileSystem.CopyFile("Resources\NewPart.sldprt", "Temp\" + filename)
            connection.CheckIn("Temp\" + filename, project, Nothing, description, "Generated by Parts Server", Nothing, Nothing, Nothing, False, Nothing)
        Catch ex As Exception
            Console.WriteLine(ex.Message)
            Environment.ExitCode = 1
        Finally
            connection.Logout()
        End Try

        Try
            My.Computer.FileSystem.DeleteFile("Temp\" + filename)
        Catch ex As Exception
        End Try
    End Sub

End Module